AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  BucketName:
    Type: String
  CodeKey:
    Type: String
Globals:
  Function:
    MemorySize: 512
    Timeout: 900

Resources:
  GetCurrentDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: !Ref BucketName
        Key: !Ref CodeKey
      Handler: build/getCurrentData/index.getCurrentData
      Runtime: nodejs12.x
