AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  BucketName:
    Type: String
  CodeKey:
    Type: String
Globals:
  Function:
    MemorySize: 512
    Timeout: 900

Resources:
  GetFantasyDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: !Ref BucketName
        Key: !Ref CodeKey
      Handler: build/getFantasyData/index.getFantasyData
      Runtime: nodejs12.x
  GetCurrentDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: !Ref BucketName
        Key: !Ref CodeKey
      Handler: build/getCurrentData/index.getCurrentData
      Runtime: nodejs12.x
  GetRollingFantasyPointAveragesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: !Ref BucketName
        Key: !Ref CodeKey
      Handler: build/getRollingFantasyPointAverages/index.getRollingFantasyPointAverages
      Runtime: nodejs12.x
  GetRecentFantasyDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
        Bucket: !Ref BucketName
        Key: !Ref CodeKey
      Handler: build/getRecentFantasyData/index.getRecentFantasyDataHandler
      Runtime: nodejs12.x
      Events:
        InvocationLevel:
          Type: Schedule
          Properties:
            Schedule: cron(0 10 * * ? *)
      Environment:
        Variables:
          AWS_KEY: !Ref AwsKey
          AWS_SECRET: !Ref AwsSecret
